/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ticket.booking;

import ticket.booking.entites.Train;
import ticket.booking.entites.User;
import ticket.booking.services.UserBookingService;
import ticket.booking.util.UserServiceUtil;

import javax.imageio.IIOException;
import javax.imageio.IIOException;
import java.io.IOException;
import java.util.*;
import java.util.function.Predicate;
import java.util.stream.Collectors;

public class App {


    public static void main(String[] args) {
        System.out.println("Running Train Booking System");

        Scanner scanner = new Scanner(System.in);
        int option = 0;
        UserBookingService userBookingService;
        String source = "SourceStation";
        String dest = "DestinationStation";

        try {
            UserBookingService userBookingService1 = new UserBookingService();

            List<Train> trains = userBookingService1.getTrains(source, dest);

            // Use the trains list as needed
            for (Train train : trains) {
                System.out.println(train);
            }
        } catch (IOException e) {
            e.printStackTrace();
        }
        try {
              userBookingService = new UserBookingService();
        }catch (IOException ex){
            System.out.println("There is something wrong");
            return;
        } catch (IOException e) {
            throw new RuntimeException(e);
        }
        Train trainSelectedForBooking = null;

        while (option!=7){
            System.out.println("Choose option");
            System.out.println("1. Sign up");
            System.out.println("2. Login");
            System.out.println("3. fetch Bookings");
            System.out.println("4. Search Trains");
            System.out.println("5. Book a Seat");
            System.out.println("6. Cancle my Bookings");
            System.out.println("7 Exit the App");
            option = scanner.nextInt();
            switch (option) {
                case 1:
                    System.out.println("Enter the username to signup");
                    String nameToSignUp = scanner.next();
                    System.out.println("Enter the password to signup");
                    String passwordToSignUp = scanner.next();
                    User userToSignup = new User(nameToSignUp, passwordToSignUp, UserServiceUtil.hashPassword(passwordToSignUp), new ArrayList<>(), UUID.randomUUID().toString());
                    userBookingService.signUp(userToSignup);
                    break;

                case 2:
                    System.out.println("Enter the username to Login");
                    String nameToLogin = scanner.next();
                    System.out.println("Enter the password to signup");
                    String  passwordToLogin = scanner.next();
                    User userToLogin = new User(nameToLogin, passwordToLogin, UserServiceUtil.hashPassword(passwordToLogin), new ArrayList<>(), UUID.randomUUID().toString());
                    try {
                        userBookingService = new UserBookingService(userToLogin);
                    } catch (IOException ex) {
                        return;
                    }
                    break;

                case 3:
                    System.out.println("Fetching your bookings");
                    userBookingService.fetchBookings();
                    break;
                case 4:
                    System.out.println("Type your source station");
                    //String source = scanner.next();
                    System.out.println("Type your destination station");
                    //String dest = scanner.next();
                    List<Train> trains = userBookingService.getTrains(source, dest);
                    int index = 1;
                    for (Train t: trains){
                        System.out.println(index+" Train id : "+t.getTrainId());
                        for (Map.Entry<String, String> entry: t.getStationTimes().entrySet()){
                            System.out.println("station "+entry.getKey()+" time: "+entry.getValue());
                        }
                    }
                    System.out.println("Select a train by typing 1,2,3...");
                   // trainSelectedForBooking = trains.get(scanner.nextInt());
                    int selectedTrainIndex = scanner.nextInt();
                    trainSelectedForBooking = trains.get(selectedTrainIndex - 1); // Adjust index to match list indices (starting from 0)
                    break;

                case 5:
                    System.out.println("Select a seat out of these seats");
                    List<List<Integer>> seats = userBookingService.fetchSeats(trainSelectedForBooking);
                    for (List<Integer> row: seats){
                        for (Integer val: row){
                            System.out.print(val+" ");
                        }
                        System.out.println();
                    }
                    System.out.println("Select the seat by typing the row and column");
                    System.out.println("Enter the row");
                    int row = scanner.nextInt();
                    System.out.println("Enter the column");
                    int col = scanner.nextInt();
                    System.out.println("Booking your seat....");
                    Boolean booked = userBookingService.bookTrainSeat(trainSelectedForBooking, row, col);
                    if(booked.equals(Boolean.TRUE)){
                        System.out.println("Booked! Enjoy your journey");
                    }else{
                        System.out.println("Can't book this seat");
                    }
                    break;
                default:
                    break;


            }

        }

    }

    }

